# This is a basic workflow to help you get started with Actions

name: Rebuild repository

# Controls when the workflow will run
on: 
  workflow_dispatch:
     inputs:
      DOWNLOAD_SHA256:
        description: 'SHA256 sum of the zip file'
        required: true
      DOWNLOAD_SIZE:
        description: 'Size of the zip file'
        required: true
      DOWNLOAD_URL:
        description: 'URL of the zip file'
        required: true
      INSTALL_SIZE:
        description: 'Size of the extracted zip file'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ${{ github.event.inputs.DOWNLOAD_SHA256 }}

